// <auto-generated>
/*
 * Progress.Nuclia REST API
 *
 * API reference for the Progress.Nuclia, covering all the endpoints related to pushing or searching contents.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Progress.Nuclia.Model;

namespace Progress.Nuclia.Model
{
    /// <summary>
    /// Error
    /// </summary>
    public partial class Error
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Error" /> class.
        /// </summary>
        /// <param name="body">body</param>
        /// <param name="code">code</param>
        /// <param name="codeStr">codeStr</param>
        /// <param name="severity">severity</param>
        /// <param name="created">created</param>
        public Error(string body, int code, string codeStr, string severity, DateTime? created)
        {
            Body = body;
            Code = code;
            CodeStr = codeStr;
            Severity = severity;
            Created = created;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Body
        /// </summary>
        [JsonPropertyName("body")]
        public string Body { get; set; }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [JsonPropertyName("code")]
        public int Code { get; set; }

        /// <summary>
        /// Gets or Sets CodeStr
        /// </summary>
        [JsonPropertyName("code_str")]
        public string CodeStr { get; set; }

        /// <summary>
        /// Gets or Sets Severity
        /// </summary>
        [JsonPropertyName("severity")]
        public string Severity { get; set; }

        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [JsonPropertyName("created")]
        public DateTime? Created { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Error {\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  CodeStr: ").Append(CodeStr).Append("\n");
            sb.Append("  Severity: ").Append(Severity).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Error" />
    /// </summary>
    public class ErrorJsonConverter : JsonConverter<Error>
    {
        /// <summary>
        /// The format to use to serialize Created
        /// </summary>
        public static string CreatedFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Error" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Error Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> body = default;
            Option<int?> code = default;
            Option<string?> codeStr = default;
            Option<string?> severity = default;
            Option<DateTime?> created = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "body":
                            body = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "code":
                            code = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "code_str":
                            codeStr = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "severity":
                            severity = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created":
                            created = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!body.IsSet)
                throw new ArgumentException("Property is required for class Error.", nameof(body));

            if (!code.IsSet)
                throw new ArgumentException("Property is required for class Error.", nameof(code));

            if (!codeStr.IsSet)
                throw new ArgumentException("Property is required for class Error.", nameof(codeStr));

            if (!severity.IsSet)
                throw new ArgumentException("Property is required for class Error.", nameof(severity));

            if (!created.IsSet)
                throw new ArgumentException("Property is required for class Error.", nameof(created));

            if (body.IsSet && body.Value == null)
                throw new ArgumentNullException(nameof(body), "Property is not nullable for class Error.");

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class Error.");

            if (codeStr.IsSet && codeStr.Value == null)
                throw new ArgumentNullException(nameof(codeStr), "Property is not nullable for class Error.");

            if (severity.IsSet && severity.Value == null)
                throw new ArgumentNullException(nameof(severity), "Property is not nullable for class Error.");

            return new Error(body.Value!, code.Value!.Value!, codeStr.Value!, severity.Value!, created.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Error" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="error"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Error error, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, error, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Error" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="error"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Error error, JsonSerializerOptions jsonSerializerOptions)
        {
            if (error.Body == null)
                throw new ArgumentNullException(nameof(error.Body), "Property is required for class Error.");

            if (error.CodeStr == null)
                throw new ArgumentNullException(nameof(error.CodeStr), "Property is required for class Error.");

            if (error.Severity == null)
                throw new ArgumentNullException(nameof(error.Severity), "Property is required for class Error.");

            writer.WriteString("body", error.Body);

            writer.WriteNumber("code", error.Code);

            writer.WriteString("code_str", error.CodeStr);

            writer.WriteString("severity", error.Severity);

            if (error.Created != null)
                writer.WriteString("created", error.Created.Value.ToString(CreatedFormat));
            else
                writer.WriteNull("created");
        }
    }
}
