// <auto-generated>
/*
 * NucliaDB REST API
 *
 * API reference for the NucliaDB, covering all the endpoints related to pushing or searching contents.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Progress.Nuclia.Model;

namespace Progress.Nuclia.Model
{
    /// <summary>
    /// List of keyword filter expressions to apply to the retrieval step. The text block search will only be performed on the documents that contain the specified keywords. The filters are case-insensitive, and only alphanumeric characters and spaces are allowed. Filtering examples can be found here: https://docs.nuclia.dev/docs/rag/advanced/search-filters
    /// </summary>
    public partial class KeywordFilters
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KeywordFilters" /> class.
        /// </summary>
        /// <param name="list"></param>
        /// <param name="list1"></param>
        internal KeywordFilters(Option<List<string>?> list, Option<List<Filter>?> list1)
        {
            ListOption = list;
            List1Option = list1;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="KeywordFilters" /> class.
        /// </summary>
        /// <param name="list"></param>
        public KeywordFilters(List<string>? list)
        {
            List = list;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="KeywordFilters" /> class.
        /// </summary>
        /// <param name="list1"></param>
        public KeywordFilters(List<Filter>? list1)
        {
            List1 = list1;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="KeywordFilters" /> class.
        /// </summary>
        public KeywordFilters()
        {
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of List
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal Option<List<string>?> ListOption { get; private set; }

        /// <summary>
        /// Gets or Sets List
        /// </summary>
        public List<string>? List { get { return this.ListOption; } set { this.ListOption = new(value); } }

        /// <summary>
        /// Used to track the state of List1
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal Option<List<Filter>?> List1Option { get; private set; }

        /// <summary>
        /// Gets or Sets List1
        /// </summary>
        public List<Filter>? List1 { get { return this.List1Option; } set { this.List1Option = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KeywordFilters {\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="KeywordFilters" />
    /// </summary>
    public class KeywordFiltersJsonConverter : JsonConverter<KeywordFilters>
    {
        /// <summary>
        /// Deserializes json to <see cref="KeywordFilters" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override KeywordFilters Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            List<string>? list = default;
            List<Filter>? list1 = default;

            Utf8JsonReader utf8JsonReaderAnyOf = utf8JsonReader;
            while (utf8JsonReaderAnyOf.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReaderAnyOf.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReaderAnyOf.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReaderAnyOf.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReaderAnyOf.CurrentDepth)
                    break;

                if (utf8JsonReaderAnyOf.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReaderAnyOf.CurrentDepth - 1)
                {
                    Utf8JsonReader utf8JsonReaderList = utf8JsonReader;
                    ClientUtils.TryDeserialize<List<string>?>(ref utf8JsonReaderList, jsonSerializerOptions, out list);

                    Utf8JsonReader utf8JsonReaderList1 = utf8JsonReader;
                    ClientUtils.TryDeserialize<List<Filter>?>(ref utf8JsonReaderList1, jsonSerializerOptions, out list1);
                }
            }

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        default:
                            break;
                    }
                }
            }

            Option<List<string>?> listParsedValue = list == null
                ? default
                : new Option<List<string>?>(list);
            Option<List<Filter>?> list1ParsedValue = list1 == null
                ? default
                : new Option<List<Filter>?>(list1);
            return new KeywordFilters(listParsedValue, list1ParsedValue);
        }

        /// <summary>
        /// Serializes a <see cref="KeywordFilters" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="keywordFilters"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, KeywordFilters keywordFilters, JsonSerializerOptions jsonSerializerOptions)
        {
            if (keywordFilters.List1Option.IsSet && keywordFilters.List1Option.Value != null)
            {
                writer.WriteStartObject();
                //List&lt;Filter&gt;JsonConverter listltFiltergtJsonConverter = (List&lt;Filter&gt;JsonConverter) jsonSerializerOptions.Converters.First(c => c.CanConvert(keywordFilters.List1Option.Value.GetType()));
                //listltFiltergtJsonConverter.WriteProperties(writer, keywordFilters.List1Option.Value, jsonSerializerOptions);
                writer.WriteEndObject();
            }

        }
    }
}
