// <auto-generated>
/*
 * NucliaDB REST API
 *
 * API reference for the NucliaDB, covering all the endpoints related to pushing or searching contents.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Progress.Nuclia.Model;

namespace Progress.Nuclia.Model
{
    /// <summary>
    /// NotOperand
    /// </summary>
    public partial class NotOperand
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="andFieldFilterExpression"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(AndFieldFilterExpression andFieldFilterExpression, string language)
        {
            AndFieldFilterExpression = andFieldFilterExpression;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="orFieldFilterExpression"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(OrFieldFilterExpression orFieldFilterExpression, string language)
        {
            OrFieldFilterExpression = orFieldFilterExpression;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="notFieldFilterExpression"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(NotFieldFilterExpression notFieldFilterExpression, string language)
        {
            NotFieldFilterExpression = notFieldFilterExpression;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="resource"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(Resource resource, string language)
        {
            Resource = resource;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="field"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(Field field, string language)
        {
            Field = field;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="keyword"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(Keyword keyword, string language)
        {
            Keyword = keyword;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="dateCreated"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(DateCreated dateCreated, string language)
        {
            DateCreated = dateCreated;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="dateModified"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(DateModified dateModified, string language)
        {
            DateModified = dateModified;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="nucliadbModelsFiltersLabel"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(NucliadbModelsFiltersLabel nucliadbModelsFiltersLabel, string language)
        {
            NucliadbModelsFiltersLabel = nucliadbModelsFiltersLabel;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="resourceMimetype"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(ResourceMimetype resourceMimetype, string language)
        {
            ResourceMimetype = resourceMimetype;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="fieldMimetype"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(FieldMimetype fieldMimetype, string language)
        {
            FieldMimetype = fieldMimetype;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="entity"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(Entity entity, string language)
        {
            Entity = entity;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="language1"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(Language language1, string language)
        {
            Language1 = language1;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="originTag"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(OriginTag originTag, string language)
        {
            OriginTag = originTag;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="originMetadata"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(OriginMetadata originMetadata, string language)
        {
            OriginMetadata = originMetadata;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="originPath"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(OriginPath originPath, string language)
        {
            OriginPath = originPath;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="originSource"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(OriginSource originSource, string language)
        {
            OriginSource = originSource;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="originCollaborator"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(OriginCollaborator originCollaborator, string language)
        {
            OriginCollaborator = originCollaborator;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="nucliadbModelsFiltersGenerated"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        internal NotOperand(NucliadbModelsFiltersGenerated nucliadbModelsFiltersGenerated, string language)
        {
            NucliadbModelsFiltersGenerated = nucliadbModelsFiltersGenerated;
            Language = language;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand" /> class.
        /// </summary>
        /// <param name="language">The code of the language to match, e.g: en</param>
        public NotOperand(string language)
        {
            Language = language;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets AndFieldFilterExpression
        /// </summary>
        public AndFieldFilterExpression? AndFieldFilterExpression { get; set; }

        /// <summary>
        /// Gets or Sets OrFieldFilterExpression
        /// </summary>
        public OrFieldFilterExpression? OrFieldFilterExpression { get; set; }

        /// <summary>
        /// Gets or Sets NotFieldFilterExpression
        /// </summary>
        public NotFieldFilterExpression? NotFieldFilterExpression { get; set; }

        /// <summary>
        /// Gets or Sets Resource
        /// </summary>
        public Resource? Resource { get; set; }

        /// <summary>
        /// Gets or Sets Field
        /// </summary>
        public Field? Field { get; set; }

        /// <summary>
        /// Gets or Sets Keyword
        /// </summary>
        public Keyword? Keyword { get; set; }

        /// <summary>
        /// Gets or Sets DateCreated
        /// </summary>
        public DateCreated? DateCreated { get; set; }

        /// <summary>
        /// Gets or Sets DateModified
        /// </summary>
        public DateModified? DateModified { get; set; }

        /// <summary>
        /// Gets or Sets NucliadbModelsFiltersLabel
        /// </summary>
        public NucliadbModelsFiltersLabel? NucliadbModelsFiltersLabel { get; set; }

        /// <summary>
        /// Gets or Sets ResourceMimetype
        /// </summary>
        public ResourceMimetype? ResourceMimetype { get; set; }

        /// <summary>
        /// Gets or Sets FieldMimetype
        /// </summary>
        public FieldMimetype? FieldMimetype { get; set; }

        /// <summary>
        /// Gets or Sets Entity
        /// </summary>
        public Entity? Entity { get; set; }

        /// <summary>
        /// Gets or Sets Language1
        /// </summary>
        public Language? Language1 { get; set; }

        /// <summary>
        /// Gets or Sets OriginTag
        /// </summary>
        public OriginTag? OriginTag { get; set; }

        /// <summary>
        /// Gets or Sets OriginMetadata
        /// </summary>
        public OriginMetadata? OriginMetadata { get; set; }

        /// <summary>
        /// Gets or Sets OriginPath
        /// </summary>
        public OriginPath? OriginPath { get; set; }

        /// <summary>
        /// Gets or Sets OriginSource
        /// </summary>
        public OriginSource? OriginSource { get; set; }

        /// <summary>
        /// Gets or Sets OriginCollaborator
        /// </summary>
        public OriginCollaborator? OriginCollaborator { get; set; }

        /// <summary>
        /// Gets or Sets NucliadbModelsFiltersGenerated
        /// </summary>
        public NucliadbModelsFiltersGenerated? NucliadbModelsFiltersGenerated { get; set; }

        /// <summary>
        /// The code of the language to match, e.g: en
        /// </summary>
        /// <value>The code of the language to match, e.g: en</value>
        [JsonPropertyName("language")]
        public string Language { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NotOperand {\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NotOperand" />
    /// </summary>
    public class NotOperandJsonConverter : JsonConverter<NotOperand>
    {
        /// <summary>
        /// Deserializes json to <see cref="NotOperand" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NotOperand Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> language = default;

            AndFieldFilterExpression? andFieldFilterExpression = default;
            OrFieldFilterExpression? orFieldFilterExpression = default;
            NotFieldFilterExpression? notFieldFilterExpression = default;
            Resource? resource = default;
            Field? field = default;
            Keyword? keyword = default;
            DateCreated? dateCreated = default;
            DateModified? dateModified = default;
            NucliadbModelsFiltersLabel? nucliadbModelsFiltersLabel = default;
            ResourceMimetype? resourceMimetype = default;
            FieldMimetype? fieldMimetype = default;
            Entity? entity = default;
            Language? language1 = default;
            OriginTag? originTag = default;
            OriginMetadata? originMetadata = default;
            OriginPath? originPath = default;
            OriginSource? originSource = default;
            OriginCollaborator? originCollaborator = default;
            NucliadbModelsFiltersGenerated? nucliadbModelsFiltersGenerated = default;

            Utf8JsonReader utf8JsonReaderOneOf = utf8JsonReader;
            while (utf8JsonReaderOneOf.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (utf8JsonReaderOneOf.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReaderOneOf.CurrentDepth - 1)
                {
                    Utf8JsonReader utf8JsonReaderAndFieldFilterExpression = utf8JsonReader;
                    ClientUtils.TryDeserialize<AndFieldFilterExpression?>(ref utf8JsonReaderAndFieldFilterExpression, jsonSerializerOptions, out andFieldFilterExpression);

                    Utf8JsonReader utf8JsonReaderOrFieldFilterExpression = utf8JsonReader;
                    ClientUtils.TryDeserialize<OrFieldFilterExpression?>(ref utf8JsonReaderOrFieldFilterExpression, jsonSerializerOptions, out orFieldFilterExpression);

                    Utf8JsonReader utf8JsonReaderNotFieldFilterExpression = utf8JsonReader;
                    ClientUtils.TryDeserialize<NotFieldFilterExpression?>(ref utf8JsonReaderNotFieldFilterExpression, jsonSerializerOptions, out notFieldFilterExpression);

                    Utf8JsonReader utf8JsonReaderResource = utf8JsonReader;
                    ClientUtils.TryDeserialize<Resource?>(ref utf8JsonReaderResource, jsonSerializerOptions, out resource);

                    Utf8JsonReader utf8JsonReaderField = utf8JsonReader;
                    ClientUtils.TryDeserialize<Field?>(ref utf8JsonReaderField, jsonSerializerOptions, out field);

                    Utf8JsonReader utf8JsonReaderKeyword = utf8JsonReader;
                    ClientUtils.TryDeserialize<Keyword?>(ref utf8JsonReaderKeyword, jsonSerializerOptions, out keyword);

                    Utf8JsonReader utf8JsonReaderDateCreated = utf8JsonReader;
                    ClientUtils.TryDeserialize<DateCreated?>(ref utf8JsonReaderDateCreated, jsonSerializerOptions, out dateCreated);

                    Utf8JsonReader utf8JsonReaderDateModified = utf8JsonReader;
                    ClientUtils.TryDeserialize<DateModified?>(ref utf8JsonReaderDateModified, jsonSerializerOptions, out dateModified);

                    Utf8JsonReader utf8JsonReaderNucliadbModelsFiltersLabel = utf8JsonReader;
                    ClientUtils.TryDeserialize<NucliadbModelsFiltersLabel?>(ref utf8JsonReaderNucliadbModelsFiltersLabel, jsonSerializerOptions, out nucliadbModelsFiltersLabel);

                    Utf8JsonReader utf8JsonReaderResourceMimetype = utf8JsonReader;
                    ClientUtils.TryDeserialize<ResourceMimetype?>(ref utf8JsonReaderResourceMimetype, jsonSerializerOptions, out resourceMimetype);

                    Utf8JsonReader utf8JsonReaderFieldMimetype = utf8JsonReader;
                    ClientUtils.TryDeserialize<FieldMimetype?>(ref utf8JsonReaderFieldMimetype, jsonSerializerOptions, out fieldMimetype);

                    Utf8JsonReader utf8JsonReaderEntity = utf8JsonReader;
                    ClientUtils.TryDeserialize<Entity?>(ref utf8JsonReaderEntity, jsonSerializerOptions, out entity);

                    Utf8JsonReader utf8JsonReaderLanguage1 = utf8JsonReader;
                    ClientUtils.TryDeserialize<Language?>(ref utf8JsonReaderLanguage1, jsonSerializerOptions, out language1);

                    Utf8JsonReader utf8JsonReaderOriginTag = utf8JsonReader;
                    ClientUtils.TryDeserialize<OriginTag?>(ref utf8JsonReaderOriginTag, jsonSerializerOptions, out originTag);

                    Utf8JsonReader utf8JsonReaderOriginMetadata = utf8JsonReader;
                    ClientUtils.TryDeserialize<OriginMetadata?>(ref utf8JsonReaderOriginMetadata, jsonSerializerOptions, out originMetadata);

                    Utf8JsonReader utf8JsonReaderOriginPath = utf8JsonReader;
                    ClientUtils.TryDeserialize<OriginPath?>(ref utf8JsonReaderOriginPath, jsonSerializerOptions, out originPath);

                    Utf8JsonReader utf8JsonReaderOriginSource = utf8JsonReader;
                    ClientUtils.TryDeserialize<OriginSource?>(ref utf8JsonReaderOriginSource, jsonSerializerOptions, out originSource);

                    Utf8JsonReader utf8JsonReaderOriginCollaborator = utf8JsonReader;
                    ClientUtils.TryDeserialize<OriginCollaborator?>(ref utf8JsonReaderOriginCollaborator, jsonSerializerOptions, out originCollaborator);

                    Utf8JsonReader utf8JsonReaderNucliadbModelsFiltersGenerated = utf8JsonReader;
                    ClientUtils.TryDeserialize<NucliadbModelsFiltersGenerated?>(ref utf8JsonReaderNucliadbModelsFiltersGenerated, jsonSerializerOptions, out nucliadbModelsFiltersGenerated);
                }
            }

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "language":
                            language = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!language.IsSet)
                throw new ArgumentException("Property is required for class NotOperand.", nameof(language));

            if (language.IsSet && language.Value == null)
                throw new ArgumentNullException(nameof(language), "Property is not nullable for class NotOperand.");

            string languageParsedValue = language.Value!;

            if (andFieldFilterExpression != null)
                return new NotOperand(andFieldFilterExpression, languageParsedValue);

            if (orFieldFilterExpression != null)
                return new NotOperand(orFieldFilterExpression, languageParsedValue);

            if (notFieldFilterExpression != null)
                return new NotOperand(notFieldFilterExpression, languageParsedValue);

            if (resource != null)
                return new NotOperand(resource, languageParsedValue);

            if (field != null)
                return new NotOperand(field, languageParsedValue);

            if (keyword != null)
                return new NotOperand(keyword, languageParsedValue);

            if (dateCreated != null)
                return new NotOperand(dateCreated, languageParsedValue);

            if (dateModified != null)
                return new NotOperand(dateModified, languageParsedValue);

            if (nucliadbModelsFiltersLabel != null)
                return new NotOperand(nucliadbModelsFiltersLabel, languageParsedValue);

            if (resourceMimetype != null)
                return new NotOperand(resourceMimetype, languageParsedValue);

            if (fieldMimetype != null)
                return new NotOperand(fieldMimetype, languageParsedValue);

            if (entity != null)
                return new NotOperand(entity, languageParsedValue);

            if (language1 != null)
                return new NotOperand(language1, languageParsedValue);

            if (originTag != null)
                return new NotOperand(originTag, languageParsedValue);

            if (originMetadata != null)
                return new NotOperand(originMetadata, languageParsedValue);

            if (originPath != null)
                return new NotOperand(originPath, languageParsedValue);

            if (originSource != null)
                return new NotOperand(originSource, languageParsedValue);

            if (originCollaborator != null)
                return new NotOperand(originCollaborator, languageParsedValue);

            if (nucliadbModelsFiltersGenerated != null)
                return new NotOperand(nucliadbModelsFiltersGenerated, languageParsedValue);

            throw new JsonException();
        }

        /// <summary>
        /// Serializes a <see cref="NotOperand" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="notOperand"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NotOperand notOperand, JsonSerializerOptions jsonSerializerOptions)
        {
        }
    }
}
