// <auto-generated>
/*
 * NucliaDB REST API
 *
 * API reference for the NucliaDB, covering all the endpoints related to pushing or searching contents.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Progress.Nuclia.Model;

namespace Progress.Nuclia.Model
{
    /// <summary>
    /// NotOperand2
    /// </summary>
    public partial class NotOperand2
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand2" /> class.
        /// </summary>
        /// <param name="andParagraphFilterExpression"></param>
        /// <param name="kind">The kind of paragraph to match</param>
        internal NotOperand2(AndParagraphFilterExpression andParagraphFilterExpression, TypeParagraph kind)
        {
            AndParagraphFilterExpression = andParagraphFilterExpression;
            Kind = kind;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand2" /> class.
        /// </summary>
        /// <param name="orParagraphFilterExpression"></param>
        /// <param name="kind">The kind of paragraph to match</param>
        internal NotOperand2(OrParagraphFilterExpression orParagraphFilterExpression, TypeParagraph kind)
        {
            OrParagraphFilterExpression = orParagraphFilterExpression;
            Kind = kind;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand2" /> class.
        /// </summary>
        /// <param name="notParagraphFilterExpression"></param>
        /// <param name="kind">The kind of paragraph to match</param>
        internal NotOperand2(NotParagraphFilterExpression notParagraphFilterExpression, TypeParagraph kind)
        {
            NotParagraphFilterExpression = notParagraphFilterExpression;
            Kind = kind;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand2" /> class.
        /// </summary>
        /// <param name="nucliadbModelsFiltersLabel"></param>
        /// <param name="kind">The kind of paragraph to match</param>
        internal NotOperand2(NucliadbModelsFiltersLabel nucliadbModelsFiltersLabel, TypeParagraph kind)
        {
            NucliadbModelsFiltersLabel = nucliadbModelsFiltersLabel;
            Kind = kind;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand2" /> class.
        /// </summary>
        /// <param name="kind1"></param>
        /// <param name="kind">The kind of paragraph to match</param>
        internal NotOperand2(Kind kind1, TypeParagraph kind)
        {
            Kind1 = kind1;
            Kind = kind;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotOperand2" /> class.
        /// </summary>
        /// <param name="kind">The kind of paragraph to match</param>
        public NotOperand2(TypeParagraph kind)
        {
            Kind = kind;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The kind of paragraph to match
        /// </summary>
        /// <value>The kind of paragraph to match</value>
        [JsonPropertyName("kind")]
        public TypeParagraph Kind { get; set; }

        /// <summary>
        /// Gets or Sets AndParagraphFilterExpression
        /// </summary>
        public AndParagraphFilterExpression? AndParagraphFilterExpression { get; set; }

        /// <summary>
        /// Gets or Sets OrParagraphFilterExpression
        /// </summary>
        public OrParagraphFilterExpression? OrParagraphFilterExpression { get; set; }

        /// <summary>
        /// Gets or Sets NotParagraphFilterExpression
        /// </summary>
        public NotParagraphFilterExpression? NotParagraphFilterExpression { get; set; }

        /// <summary>
        /// Gets or Sets NucliadbModelsFiltersLabel
        /// </summary>
        public NucliadbModelsFiltersLabel? NucliadbModelsFiltersLabel { get; set; }

        /// <summary>
        /// Gets or Sets Kind1
        /// </summary>
        public Kind? Kind1 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NotOperand2 {\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NotOperand2" />
    /// </summary>
    public class NotOperand2JsonConverter : JsonConverter<NotOperand2>
    {
        /// <summary>
        /// Deserializes json to <see cref="NotOperand2" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NotOperand2 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<TypeParagraph?> kind = default;

            AndParagraphFilterExpression? andParagraphFilterExpression = default;
            OrParagraphFilterExpression? orParagraphFilterExpression = default;
            NotParagraphFilterExpression? notParagraphFilterExpression = default;
            NucliadbModelsFiltersLabel? nucliadbModelsFiltersLabel = default;
            Kind? kind1 = default;

            Utf8JsonReader utf8JsonReaderOneOf = utf8JsonReader;
            while (utf8JsonReaderOneOf.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (utf8JsonReaderOneOf.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReaderOneOf.CurrentDepth - 1)
                {
                    Utf8JsonReader utf8JsonReaderAndParagraphFilterExpression = utf8JsonReader;
                    ClientUtils.TryDeserialize<AndParagraphFilterExpression?>(ref utf8JsonReaderAndParagraphFilterExpression, jsonSerializerOptions, out andParagraphFilterExpression);

                    Utf8JsonReader utf8JsonReaderOrParagraphFilterExpression = utf8JsonReader;
                    ClientUtils.TryDeserialize<OrParagraphFilterExpression?>(ref utf8JsonReaderOrParagraphFilterExpression, jsonSerializerOptions, out orParagraphFilterExpression);

                    Utf8JsonReader utf8JsonReaderNotParagraphFilterExpression = utf8JsonReader;
                    ClientUtils.TryDeserialize<NotParagraphFilterExpression?>(ref utf8JsonReaderNotParagraphFilterExpression, jsonSerializerOptions, out notParagraphFilterExpression);

                    Utf8JsonReader utf8JsonReaderNucliadbModelsFiltersLabel = utf8JsonReader;
                    ClientUtils.TryDeserialize<NucliadbModelsFiltersLabel?>(ref utf8JsonReaderNucliadbModelsFiltersLabel, jsonSerializerOptions, out nucliadbModelsFiltersLabel);

                    Utf8JsonReader utf8JsonReaderKind1 = utf8JsonReader;
                    ClientUtils.TryDeserialize<Kind?>(ref utf8JsonReaderKind1, jsonSerializerOptions, out kind1);
                }
            }

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "kind":
                            string? kindRawValue = utf8JsonReader.GetString();
                            if (kindRawValue != null)
                                kind = new Option<TypeParagraph?>(TypeParagraphValueConverter.FromStringOrDefault(kindRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!kind.IsSet)
                throw new ArgumentException("Property is required for class NotOperand2.", nameof(kind));

            if (kind.IsSet && kind.Value == null)
                throw new ArgumentNullException(nameof(kind), "Property is not nullable for class NotOperand2.");

            TypeParagraph kindParsedValue = (TypeParagraph)kind.Value;

            if (andParagraphFilterExpression != null)
                return new NotOperand2(andParagraphFilterExpression, kindParsedValue);

            if (orParagraphFilterExpression != null)
                return new NotOperand2(orParagraphFilterExpression, kindParsedValue);

            if (notParagraphFilterExpression != null)
                return new NotOperand2(notParagraphFilterExpression, kindParsedValue);

            if (nucliadbModelsFiltersLabel != null)
                return new NotOperand2(nucliadbModelsFiltersLabel, kindParsedValue);

            if (kind1 != null)
                return new NotOperand2(kind1, kindParsedValue);

            throw new JsonException();
        }

        /// <summary>
        /// Serializes a <see cref="NotOperand2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="notOperand2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NotOperand2 notOperand2, JsonSerializerOptions jsonSerializerOptions)
        {
        }
    }
}
