// <auto-generated>
/*
 * NucliaDB REST API
 *
 * API reference for the NucliaDB, covering all the endpoints related to pushing or searching contents.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Progress.Nuclia.Model;

namespace Progress.Nuclia.Model
{
    /// <summary>
    /// Filter to apply to resources
    /// </summary>
    public partial class ResourceFilters
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceFilters" /> class.
        /// </summary>
        /// <param name="andResourceFilterExpression"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        /// <param name="label">label</param>
        internal ResourceFilters(AndResourceFilterExpression andResourceFilterExpression, string language, Option<string?> label = default)
        {
            AndResourceFilterExpression = andResourceFilterExpression;
            Language = language;
            LabelOption = label;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceFilters" /> class.
        /// </summary>
        /// <param name="orResourceFilterExpression"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        /// <param name="label">label</param>
        internal ResourceFilters(OrResourceFilterExpression orResourceFilterExpression, string language, Option<string?> label = default)
        {
            OrResourceFilterExpression = orResourceFilterExpression;
            Language = language;
            LabelOption = label;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceFilters" /> class.
        /// </summary>
        /// <param name="notResourceFilterExpression"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        /// <param name="label">label</param>
        internal ResourceFilters(NotResourceFilterExpression notResourceFilterExpression, string language, Option<string?> label = default)
        {
            NotResourceFilterExpression = notResourceFilterExpression;
            Language = language;
            LabelOption = label;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceFilters" /> class.
        /// </summary>
        /// <param name="nucliadbModelsFiltersResource"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        /// <param name="label">label</param>
        internal ResourceFilters(NucliadbModelsFiltersResource nucliadbModelsFiltersResource, string language, Option<string?> label = default)
        {
            NucliadbModelsFiltersResource = nucliadbModelsFiltersResource;
            Language = language;
            LabelOption = label;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceFilters" /> class.
        /// </summary>
        /// <param name="dateCreated"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        /// <param name="label">label</param>
        internal ResourceFilters(DateCreated dateCreated, string language, Option<string?> label = default)
        {
            DateCreated = dateCreated;
            Language = language;
            LabelOption = label;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceFilters" /> class.
        /// </summary>
        /// <param name="dateModified"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        /// <param name="label">label</param>
        internal ResourceFilters(DateModified dateModified, string language, Option<string?> label = default)
        {
            DateModified = dateModified;
            Language = language;
            LabelOption = label;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceFilters" /> class.
        /// </summary>
        /// <param name="label1"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        /// <param name="label">label</param>
        internal ResourceFilters(Label label1, string language, Option<string?> label = default)
        {
            Label1 = label1;
            Language = language;
            LabelOption = label;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceFilters" /> class.
        /// </summary>
        /// <param name="resourceMimetype"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        /// <param name="label">label</param>
        internal ResourceFilters(ResourceMimetype resourceMimetype, string language, Option<string?> label = default)
        {
            ResourceMimetype = resourceMimetype;
            Language = language;
            LabelOption = label;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceFilters" /> class.
        /// </summary>
        /// <param name="language1"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        /// <param name="label">label</param>
        internal ResourceFilters(Language language1, string language, Option<string?> label = default)
        {
            Language1 = language1;
            Language = language;
            LabelOption = label;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceFilters" /> class.
        /// </summary>
        /// <param name="originTag"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        /// <param name="label">label</param>
        internal ResourceFilters(OriginTag originTag, string language, Option<string?> label = default)
        {
            OriginTag = originTag;
            Language = language;
            LabelOption = label;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceFilters" /> class.
        /// </summary>
        /// <param name="originMetadata"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        /// <param name="label">label</param>
        internal ResourceFilters(OriginMetadata originMetadata, string language, Option<string?> label = default)
        {
            OriginMetadata = originMetadata;
            Language = language;
            LabelOption = label;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceFilters" /> class.
        /// </summary>
        /// <param name="originPath"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        /// <param name="label">label</param>
        internal ResourceFilters(OriginPath originPath, string language, Option<string?> label = default)
        {
            OriginPath = originPath;
            Language = language;
            LabelOption = label;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceFilters" /> class.
        /// </summary>
        /// <param name="originSource"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        /// <param name="label">label</param>
        internal ResourceFilters(OriginSource originSource, string language, Option<string?> label = default)
        {
            OriginSource = originSource;
            Language = language;
            LabelOption = label;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceFilters" /> class.
        /// </summary>
        /// <param name="originCollaborator"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        /// <param name="label">label</param>
        internal ResourceFilters(OriginCollaborator originCollaborator, string language, Option<string?> label = default)
        {
            OriginCollaborator = originCollaborator;
            Language = language;
            LabelOption = label;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceFilters" /> class.
        /// </summary>
        /// <param name="status"></param>
        /// <param name="language">The code of the language to match, e.g: en</param>
        /// <param name="label">label</param>
        internal ResourceFilters(Status status, string language, Option<string?> label = default)
        {
            Status = status;
            Language = language;
            LabelOption = label;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceFilters" /> class.
        /// </summary>
        /// <param name="language">The code of the language to match, e.g: en</param>
        public ResourceFilters(string language)
        {
            Language = language;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets AndResourceFilterExpression
        /// </summary>
        public AndResourceFilterExpression? AndResourceFilterExpression { get; set; }

        /// <summary>
        /// Gets or Sets OrResourceFilterExpression
        /// </summary>
        public OrResourceFilterExpression? OrResourceFilterExpression { get; set; }

        /// <summary>
        /// Gets or Sets NotResourceFilterExpression
        /// </summary>
        public NotResourceFilterExpression? NotResourceFilterExpression { get; set; }

        /// <summary>
        /// Gets or Sets NucliadbModelsFiltersResource
        /// </summary>
        public NucliadbModelsFiltersResource? NucliadbModelsFiltersResource { get; set; }

        /// <summary>
        /// Gets or Sets DateCreated
        /// </summary>
        public DateCreated? DateCreated { get; set; }

        /// <summary>
        /// Gets or Sets DateModified
        /// </summary>
        public DateModified? DateModified { get; set; }

        /// <summary>
        /// Gets or Sets Label1
        /// </summary>
        public Label? Label1 { get; set; }

        /// <summary>
        /// Gets or Sets ResourceMimetype
        /// </summary>
        public ResourceMimetype? ResourceMimetype { get; set; }

        /// <summary>
        /// Gets or Sets Language1
        /// </summary>
        public Language? Language1 { get; set; }

        /// <summary>
        /// Gets or Sets OriginTag
        /// </summary>
        public OriginTag? OriginTag { get; set; }

        /// <summary>
        /// Gets or Sets OriginMetadata
        /// </summary>
        public OriginMetadata? OriginMetadata { get; set; }

        /// <summary>
        /// Gets or Sets OriginPath
        /// </summary>
        public OriginPath? OriginPath { get; set; }

        /// <summary>
        /// Gets or Sets OriginSource
        /// </summary>
        public OriginSource? OriginSource { get; set; }

        /// <summary>
        /// Gets or Sets OriginCollaborator
        /// </summary>
        public OriginCollaborator? OriginCollaborator { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        public Status? Status { get; set; }

        /// <summary>
        /// The code of the language to match, e.g: en
        /// </summary>
        /// <value>The code of the language to match, e.g: en</value>
        [JsonPropertyName("language")]
        public string Language { get; set; }

        /// <summary>
        /// Used to track the state of Label
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal Option<string?> LabelOption { get; private set; }

        /// <summary>
        /// Gets or Sets Label
        /// </summary>
        [JsonPropertyName("label")]
        public string? Label { get { return this.LabelOption; } set { this.LabelOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResourceFilters {\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ResourceFilters" />
    /// </summary>
    public class ResourceFiltersJsonConverter : JsonConverter<ResourceFilters>
    {
        /// <summary>
        /// Deserializes json to <see cref="ResourceFilters" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ResourceFilters Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> language = default;
            Option<string?> label = default;

            AndResourceFilterExpression? andResourceFilterExpression = default;
            OrResourceFilterExpression? orResourceFilterExpression = default;
            NotResourceFilterExpression? notResourceFilterExpression = default;
            NucliadbModelsFiltersResource? nucliadbModelsFiltersResource = default;
            DateCreated? dateCreated = default;
            DateModified? dateModified = default;
            Label? label1 = default;
            ResourceMimetype? resourceMimetype = default;
            Language? language1 = default;
            OriginTag? originTag = default;
            OriginMetadata? originMetadata = default;
            OriginPath? originPath = default;
            OriginSource? originSource = default;
            OriginCollaborator? originCollaborator = default;
            Status? status = default;

            Utf8JsonReader utf8JsonReaderOneOf = utf8JsonReader;
            while (utf8JsonReaderOneOf.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (utf8JsonReaderOneOf.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReaderOneOf.CurrentDepth - 1)
                {
                    Utf8JsonReader utf8JsonReaderAndResourceFilterExpression = utf8JsonReader;
                    ClientUtils.TryDeserialize<AndResourceFilterExpression?>(ref utf8JsonReaderAndResourceFilterExpression, jsonSerializerOptions, out andResourceFilterExpression);

                    Utf8JsonReader utf8JsonReaderOrResourceFilterExpression = utf8JsonReader;
                    ClientUtils.TryDeserialize<OrResourceFilterExpression?>(ref utf8JsonReaderOrResourceFilterExpression, jsonSerializerOptions, out orResourceFilterExpression);

                    Utf8JsonReader utf8JsonReaderNotResourceFilterExpression = utf8JsonReader;
                    ClientUtils.TryDeserialize<NotResourceFilterExpression?>(ref utf8JsonReaderNotResourceFilterExpression, jsonSerializerOptions, out notResourceFilterExpression);

                    Utf8JsonReader utf8JsonReaderNucliadbModelsFiltersResource = utf8JsonReader;
                    ClientUtils.TryDeserialize<NucliadbModelsFiltersResource?>(ref utf8JsonReaderNucliadbModelsFiltersResource, jsonSerializerOptions, out nucliadbModelsFiltersResource);

                    Utf8JsonReader utf8JsonReaderDateCreated = utf8JsonReader;
                    ClientUtils.TryDeserialize<DateCreated?>(ref utf8JsonReaderDateCreated, jsonSerializerOptions, out dateCreated);

                    Utf8JsonReader utf8JsonReaderDateModified = utf8JsonReader;
                    ClientUtils.TryDeserialize<DateModified?>(ref utf8JsonReaderDateModified, jsonSerializerOptions, out dateModified);

                    Utf8JsonReader utf8JsonReaderLabel1 = utf8JsonReader;
                    ClientUtils.TryDeserialize<Label?>(ref utf8JsonReaderLabel1, jsonSerializerOptions, out label1);

                    Utf8JsonReader utf8JsonReaderResourceMimetype = utf8JsonReader;
                    ClientUtils.TryDeserialize<ResourceMimetype?>(ref utf8JsonReaderResourceMimetype, jsonSerializerOptions, out resourceMimetype);

                    Utf8JsonReader utf8JsonReaderLanguage1 = utf8JsonReader;
                    ClientUtils.TryDeserialize<Language?>(ref utf8JsonReaderLanguage1, jsonSerializerOptions, out language1);

                    Utf8JsonReader utf8JsonReaderOriginTag = utf8JsonReader;
                    ClientUtils.TryDeserialize<OriginTag?>(ref utf8JsonReaderOriginTag, jsonSerializerOptions, out originTag);

                    Utf8JsonReader utf8JsonReaderOriginMetadata = utf8JsonReader;
                    ClientUtils.TryDeserialize<OriginMetadata?>(ref utf8JsonReaderOriginMetadata, jsonSerializerOptions, out originMetadata);

                    Utf8JsonReader utf8JsonReaderOriginPath = utf8JsonReader;
                    ClientUtils.TryDeserialize<OriginPath?>(ref utf8JsonReaderOriginPath, jsonSerializerOptions, out originPath);

                    Utf8JsonReader utf8JsonReaderOriginSource = utf8JsonReader;
                    ClientUtils.TryDeserialize<OriginSource?>(ref utf8JsonReaderOriginSource, jsonSerializerOptions, out originSource);

                    Utf8JsonReader utf8JsonReaderOriginCollaborator = utf8JsonReader;
                    ClientUtils.TryDeserialize<OriginCollaborator?>(ref utf8JsonReaderOriginCollaborator, jsonSerializerOptions, out originCollaborator);

                    Utf8JsonReader utf8JsonReaderStatus = utf8JsonReader;
                    ClientUtils.TryDeserialize<Status?>(ref utf8JsonReaderStatus, jsonSerializerOptions, out status);
                }
            }

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "language":
                            language = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "label":
                            label = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!language.IsSet)
                throw new ArgumentException("Property is required for class ResourceFilters.", nameof(language));

            if (language.IsSet && language.Value == null)
                throw new ArgumentNullException(nameof(language), "Property is not nullable for class ResourceFilters.");

            if (label.IsSet && label.Value == null)
                throw new ArgumentNullException(nameof(label), "Property is not nullable for class ResourceFilters.");

            string languageParsedValue = language.Value!;

            if (andResourceFilterExpression != null)
                return new ResourceFilters(andResourceFilterExpression, languageParsedValue, label);

            if (orResourceFilterExpression != null)
                return new ResourceFilters(orResourceFilterExpression, languageParsedValue, label);

            if (notResourceFilterExpression != null)
                return new ResourceFilters(notResourceFilterExpression, languageParsedValue, label);

            if (nucliadbModelsFiltersResource != null)
                return new ResourceFilters(nucliadbModelsFiltersResource, languageParsedValue, label);

            if (dateCreated != null)
                return new ResourceFilters(dateCreated, languageParsedValue, label);

            if (dateModified != null)
                return new ResourceFilters(dateModified, languageParsedValue, label);

            if (label1 != null)
                return new ResourceFilters(label1, languageParsedValue, label);

            if (resourceMimetype != null)
                return new ResourceFilters(resourceMimetype, languageParsedValue, label);

            if (language1 != null)
                return new ResourceFilters(language1, languageParsedValue, label);

            if (originTag != null)
                return new ResourceFilters(originTag, languageParsedValue, label);

            if (originMetadata != null)
                return new ResourceFilters(originMetadata, languageParsedValue, label);

            if (originPath != null)
                return new ResourceFilters(originPath, languageParsedValue, label);

            if (originSource != null)
                return new ResourceFilters(originSource, languageParsedValue, label);

            if (originCollaborator != null)
                return new ResourceFilters(originCollaborator, languageParsedValue, label);

            if (status != null)
                return new ResourceFilters(status, languageParsedValue, label);

            throw new JsonException();
        }

        /// <summary>
        /// Serializes a <see cref="ResourceFilters" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="resourceFilters"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ResourceFilters resourceFilters, JsonSerializerOptions jsonSerializerOptions)
        {
        }
    }
}
