// <auto-generated>
/*
 * Progress.Nuclia REST API
 *
 * API reference for the Progress.Nuclia, covering all the endpoints related to pushing or searching contents.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using Progress.Nuclia.Model;

namespace Progress.Nuclia.Model
{
    /// <summary>
    /// ValidationErrorLocInner
    /// </summary>
    public partial class ValidationErrorLocInner
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationErrorLocInner" /> class.
        /// </summary>
        /// <param name="string"></param>
        /// <param name="int"></param>
        internal ValidationErrorLocInner(Option<string?> @string, Option<int?> @int)
        {
            StringOption = @string;
            IntOption = @int;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationErrorLocInner" /> class.
        /// </summary>
        /// <param name="string"></param>
        public ValidationErrorLocInner(string? @string)
        {
            String = @string;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationErrorLocInner" /> class.
        /// </summary>
        /// <param name="int"></param>
        public ValidationErrorLocInner(int? @int)
        {
            Int = @int;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationErrorLocInner" /> class.
        /// </summary>
        public ValidationErrorLocInner()
        {
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of String
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal Option<string?> StringOption { get; private set; }

        /// <summary>
        /// Gets or Sets String
        /// </summary>
        public string? String { get { return this.StringOption; } set { this.StringOption = new(value); } }

        /// <summary>
        /// Used to track the state of Int
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal Option<int?> IntOption { get; private set; }

        /// <summary>
        /// Gets or Sets Int
        /// </summary>
        public int? Int { get { return this.IntOption; } set { this.IntOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ValidationErrorLocInner {\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ValidationErrorLocInner" />
    /// </summary>
    public class ValidationErrorLocInnerJsonConverter : JsonConverter<ValidationErrorLocInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="ValidationErrorLocInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ValidationErrorLocInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            if (utf8JsonReader.TokenType == JsonTokenType.String)
            {
                var str = utf8JsonReader.GetString();
                return new ValidationErrorLocInner(str);
            }
            else if (utf8JsonReader.TokenType == JsonTokenType.Number)
            {
                var num = utf8JsonReader.GetInt32();
                return new ValidationErrorLocInner(num);
            }
            else if (utf8JsonReader.TokenType == JsonTokenType.Null)
            {
                return new ValidationErrorLocInner();
            }
            
            throw new JsonException($"Expected string or int value, but got {utf8JsonReader.TokenType}");
        }

        /// <summary>
        /// Serializes a <see cref="ValidationErrorLocInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="validationErrorLocInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ValidationErrorLocInner validationErrorLocInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (validationErrorLocInner.StringOption.IsSet && validationErrorLocInner.StringOption.Value != null)
                writer.WriteStringValue(validationErrorLocInner.StringOption.Value);

            else if (validationErrorLocInner.IntOption.IsSet && validationErrorLocInner.IntOption.Value != null)
                writer.WriteNumberValue(validationErrorLocInner.IntOption.Value.Value);

        }
    }
}
